project:
  type: website
  output-dir: docs
website:
  title: "The MIND Lab"
  navbar:
    logo: "images/icon.png"
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: tools.qmd
        text: Tools
      - href: people.qmd
        text: People
format:
  html:
    theme:
      - litera
    css: styles.css

editor: source

